version: '3.8'

services:
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../api:/app
    environment:
      - PYTHONUNBUFFERED=1
